[general]
output_dir = 'outputs/cub_200/imagebind/naive/'
model_flag = 'imagebind'
training_embeds_path = 'None'
gpu_num = 0
epochs =  [1000]
batch_size = 2
epsilon = 16
lr = 0.02
seed = 0
number_images = 100
gamma_epochs = 300
modality = 'vision'
dataset_flag = 'cub_200'
max_epochs = 1000
train_test_flag = 'False'
