[general]
output_dir = 'outputs/mscoco/openclip_300/'
model_flag = 'openclip'
training_embeds_path = 'outputs/embeddings/mscoco_openclip_training_embeddings.npy'
gpu_num = 0
epochs =  [300]
batch_size = 50
epsilon = 16
lr = 0.02
seed = 0
number_images = 100
gamma_epochs = 300
modality = 'vision'
dataset_flag = 'mscoco'
max_epochs=300
train_test_flag = 'False'
