[general]
output_dir = 'outputs/audiocap/audioclip/'
model_flag = 'audioclip'
gpu_num = 0
epochs =  [1000]
batch_size = 1
epsilon = 0.05
lr = 0.02
seed = 0
number_images = 100
gamma_epochs = 300
modality = 'audio'
dataset_flag = 'audiocaps'
max_epochs=1000
cross_modality = 'True'
train_test_flag = 'False'
training_embeds_path = 'None'
